'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Course
    Public Property Id As Integer
    Public Property CourseCode As String
    Public Property CourseName As String
    Public Property CourseDescription As String
    Public Property CourseCost As Nullable(Of Decimal)

End Class
